### ISSUE TITLE
Trying to compile on Ubuntu16.04,could not find Accelerate.h

### ISSUE THREAD

**Issue by QMonteCarlo** [frobelbest/GSLAM#2]
Hello! I'm trying to compile your project on Ubuntu 16.04, I have compiled the dependencies, but when trying to compile the library, I could not find the Accelerate/Accelerate.h, could you give me a hint which library it belongs to or where it comes from?

**Comment by frobelbest** [comment]
Hi I include this file because it is required to compile with avx
instructions on Mac.
On Linux you can directly include the head for avx #include <immintrin.h>.

**Comment by frobelbest** [comment]
@QMonteCarlo Hi I include this file because it is required to compile with avx
instructions on Mac.
On Linux you can directly include the head for avx #include <immintrin.h>.

**Comment by QMonteCarlo** [comment]
Thanks, this error solved. But there are still too many compilation errors, I'll keep working on it.

**Comment by frobelbest** [comment]
@QMonteCarlo You are always welcome to list the errors here. Current version is complied in Xcode.
I'll try to set a cmake file for the project in the future.

**Comment by go925315** [comment]
@QMonteCarlo Hello! Do you willing to share the cmake?

**Comment by QMonteCarlo** [comment]
@go925315 I'd like to. But the cmake has not work by now, because extra problems emerged, I need to modify the original code, this may takes long time. 
If you are still interested, I'll take some time to review my change and then share it.

**Comment by go925315** [comment]
@QMonteCarlo My cmake can be work. But I want to run TUM Dataset, he can't work. Can you help me?
[CMakeLists.txt](https://github.com/frobelbest/GSLAM/files/2156787/CMakeLists.txt)

**Comment by frobelbest** [comment]
@go925315 
Hi For TUM dataset since there is no gyroscope available.
There are two options 
1. use "groundtruth" rotation as input. But coordinate alignment is necessary. Even you get it aligned, the "groundtruth" still has non-negligible noise.
2. In my paper, to run the experiments on TUM I use some five-pt algorithm like algorithm to estimate the rotation(as well as translation if you want). You can try different 5-pt methods from opengv and the classic nitster's 5pt turns out to be the best.

**Comment by Dorothy-2016** [comment]
@go925315 have you successfully run this code on linux? I tried to use your CMakeLists.txt to compile this code on linux, but still has some errors, like error:'FILE' does not name a type extern FILE *svd_fatalReadFile(char *filename) ... have you encountered these kind of  errors?

**Comment by ghost** [comment]
@go925315, @Dorothy-2016 have you managed to build this project on Linux? I faced also errors like:
> 'FILE' does not name a type extern FILE *svd_fatalReadFile(char *filename).

**Comment by AlejandroSilvestri** [comment]
@Dorothy-2016 , @geothan 

For the specific 'FILE' problem, add to svdutil.hpp

    #include <stdio.h>

I'm trying to build it on Ubuntu, a lot of effort and still no result.  You will have to rewrite main.

**Comment by ghost** [comment]
@AlejandroSilvestri, @go925315, @Dorothy-2016
Some important corrections towards project building are:
1. Add "using namespace std;" in files: Frame.h, KeyFrame.h, KeyFrameDatabase.h
2. Change FALSE to false in system.cpp in lines 149,150,151
3. Install Library CBLAS and update the above cmakelists.txt: 

include_directories(
……...
**${BLAS_INCLUDE_DIRS}**
)

target_link_libraries(${PROJECT_NAME}
……….
**${BLAS_LIBRARIES}**
)
My build process stuck in system.cpp with the error:
error: ‘GSLAM::ORBVocabulary {aka class DBoW2::TemplatedVocabulary<cv::Mat, DBoW2::FORB>}’ has no member named ‘loadFromTextFile’
         bool bVocLoad = mpVocabulary->loadFromTextFile(strVocFile);

Most probably the implementation of loadFromTextFile is missing? Has anyone found the solution for this problem?

**Comment by AlejandroSilvestri** [comment]
@geothan 

I compiled after a lot of corrections, mainly to silence warnings.
I adapted main code deleting Apple's code and rewriting to open video with opencv's VideoCapture.
I put my own faster

    mpVocabulary->loadFrom**Binary**File(strVocFile);

But right now I see every call to "visualize" is commented out.  No visualization?

Does someone succeed running gslam?
